import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { ERROR_MESSAGES } from '../../../lib/constants';
import { getAdminDbClient } from '../../../services/db';
import { authorizeCareRequest } from '../../../services/careTeam';
import { parseJsonBody } from '../../../services/apiRequestBody';
import { logger } from '../../../services/logger';

// Push subscription registry (M15): any circle member may register the
// browser subscription that the fill-reminder cron later notifies. Rows are
// keyed by the push-service endpoint, so re-subscribing (or switching the
// logged-in account on the same browser) upserts ownership in place.

const ALL_ROLES = ['owner', 'caregiver', 'clinician', 'recipient'] as const;

// The endpoint is a push-service URL generated by the browser (FCM, Mozilla
// autopush, APNs web push...) — https-only, but never a fixed domain.
const subscriptionSchema = z.object({
  endpoint: z.string().url().max(1000).startsWith('https://'),
  keys: z.object({
    p256dh: z.string().min(1).max(200),
    auth: z.string().min(1).max(100),
  }),
});

export async function POST(req: NextRequest): Promise<NextResponse> {
  const auth = await authorizeCareRequest(req, ALL_ROLES);
  if (!auth.ok) return auth.response;
  const { user } = auth;

  const body = await parseJsonBody(req, subscriptionSchema);
  if (!body.ok) return body.response;
  const subscription = body.data;

  const { error } = await getAdminDbClient().from('push_subscriptions').upsert(
    {
      user_id: user.id,
      endpoint: subscription.endpoint,
      p256dh: subscription.keys.p256dh,
      auth: subscription.keys.auth,
    },
    { onConflict: 'endpoint' },
  );
  if (error) {
    logger.error(
      'push: subscription upsert failed',
      { route: '/api/push', action: 'subscribe' },
      error,
    );
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 },
    );
  }

  logger.info('push: subscription stored', {
    route: '/api/push',
    action: 'subscribed',
    userId: user.id,
  });
  return NextResponse.json({ subscribed: true }, { status: 201 });
}

export async function DELETE(req: NextRequest): Promise<NextResponse> {
  const auth = await authorizeCareRequest(req, ALL_ROLES);
  if (!auth.ok) return auth.response;
  const { user } = auth;

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      { error: ERROR_MESSAGES.VALIDATION_FAILED },
      { status: 400 },
    );
  }
  const parsed = z
    .object({ endpoint: z.string().url().max(1000) })
    .safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: ERROR_MESSAGES.VALIDATION_FAILED },
      { status: 400 },
    );
  }

  // Scoped to the caller's own rows — one user cannot drop another's device
  const { error } = await getAdminDbClient()
    .from('push_subscriptions')
    .delete()
    .eq('endpoint', parsed.data.endpoint)
    .eq('user_id', user.id);
  if (error) {
    logger.error(
      'push: subscription delete failed',
      { route: '/api/push', action: 'unsubscribe' },
      error,
    );
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 },
    );
  }
  return NextResponse.json({ unsubscribed: true });
}
